drop table �v�Z�@�p��;
create table �v�Z�@�p�� (�p�� text, ���ރR�[�h varchar, ���l1A���� char(16));
create index �v�Z�@�p��index1 on �v�Z�@�p�� using btree (�p��);
create index �v�Z�@�p��index2 on �v�Z�@�p�� using hash (���ރR�[�h);
insert into �v�Z�@�p�� values('�R���s���[�^�f�B�X�v���C','�@A01��');
insert into �v�Z�@�p�� values('�R���s���[�^�O���t�B�b�N�X','��B10��');
insert into �v�Z�@�p�� values('�R���s���[�^�v���O���}�[','�lZ01��');
vacuum �v�Z�@�p��;
select * from �v�Z�@�p��;
select * from �v�Z�@�p�� where ���ރR�[�h = '�lZ01��';
select * from �v�Z�@�p�� where ���ރR�[�h ~* '�lz01��';
select * from �v�Z�@�p�� where ���ރR�[�h like '_Z01_';
select * from �v�Z�@�p�� where ���ރR�[�h like '_Z%';
select * from �v�Z�@�p�� where �p�� ~ '�R���s���[�^[�f�O]';
select * from �v�Z�@�p�� where �p�� ~* '�R���s���[�^[�f�O]';
select *,character_length(�p��) from �v�Z�@�p��;
select *,octet_length(�p��) from �v�Z�@�p��;
select *,position('�f' in �p��) from �v�Z�@�p��;
select *,substring(�p�� from 10 for 4) from �v�Z�@�p��;
copy �v�Z�@�p�� to stdout;
