drop table ��ٸ����;
create table ��ٸ���� (����ɱ text, ��Ƴ��� varchar, ���� varchar(16));
create index ��ٸ����index1 on ��ٸ���� using btree (����ɱ);
create index ��ٸ����index2 on ��ٸ���� using hash (��Ƴ���);
insert into ��ٸ���� values ('�����', '������', 'ơA01��');
insert into ��ٸ���� values ('������', '����ȴ����Ƴ', '��B10��');
insert into ��ٸ���� values ('����', 'ӡ��ϴǹȴ����Ƴ', '��Z01Ħ');
vacuum ��ٸ����;
select * from ��ٸ����;
select * from ��ٸ���� where ���� = '��Z01Ħ';
select * from ��ٸ���� where ���� ~* '��z01Ħ';
select * from ��ٸ���� where ���� like '_Z01_';
select * from ��ٸ���� where ���� like '_Z%';
select * from ��ٸ���� where ��Ƴ��� ~ '����[��ش��]';
select * from ��ٸ���� where ��Ƴ��� ~* '����[��ش��]';

select *, character_length(����ɱ) from ��ٸ����;
select *, octet_length(����ɱ) from ��ٸ����;
select *, position('ȴ��' in ��Ƴ���) from ��ٸ����;
select *, substring(��Ƴ��� from 3 for 6 ) from ��ٸ����;
