drop table �׻����Ѹ�;
create table �׻����Ѹ� (�Ѹ� text, ʬ�ॳ���� varchar, ����1A���� char(16));
create index �׻����Ѹ�index1 on �׻����Ѹ� using btree (�Ѹ�);
create index �׻����Ѹ�index2 on �׻����Ѹ� using hash (ʬ�ॳ����);
insert into �׻����Ѹ� values('����ԥ塼���ǥ����ץ쥤','��A01��');
insert into �׻����Ѹ� values('����ԥ塼������ե��å���','ʬB10��');
insert into �׻����Ѹ� values('����ԥ塼���ץ���ޡ�','��Z01��');
vacuum �׻����Ѹ�;
select * from �׻����Ѹ�;
select * from �׻����Ѹ� where ʬ�ॳ���� = '��Z01��';
select * from �׻����Ѹ� where ʬ�ॳ���� ~* '��z01��';
select * from �׻����Ѹ� where ʬ�ॳ���� like '_Z01_';
select * from �׻����Ѹ� where ʬ�ॳ���� like '_Z%';
select * from �׻����Ѹ� where �Ѹ� ~ '����ԥ塼��[�ǥ�]';
select * from �׻����Ѹ� where �Ѹ� ~* '����ԥ塼��[�ǥ�]';
select *,character_length(�Ѹ�) from �׻����Ѹ�;
select *,octet_length(�Ѹ�) from �׻����Ѹ�;
select *,position('��' in �Ѹ�) from �׻����Ѹ�;
select *,substring(�Ѹ� from 10 for 4) from �׻����Ѹ�;
